
public class TryCatchExample {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

	}

	public static void TryCatchExample() {
		// trata de ejecutar el código que se encuentra entre las llaves
		try {
			for (int i = -5; i < 5; i++) {
				int c = 5 / i;
				System.out.println(c);
			}
		}
		// captura la excepción de tipo ArithmeticException
		catch (ArithmeticException e) {
			System.out.println("Excepción arimética");
		}
		// captura cualquier otra excepción que pueda producirse
		catch (Exception e) {
			System.out.println("Otro error desconocido");
		}
		System.out.println("Programa finalizado");
	}

}
